# Generated by Django 2.2.7 on 2019-12-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_notebook_product_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, default='default.png', max_length=500, upload_to='Image/all_product/')),
                ('brand', models.CharField(max_length=30)),
                ('product_detail', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=100)),
                ('graphics', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('special_price', models.IntegerField(default=0)),
                ('normal_price', models.IntegerField(default=0)),
                ('save_price', models.IntegerField(default=0)),
            ],
        ),
    ]
