# Generated by Django 2.2.7 on 2019-12-19 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='add_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
