# Generated by Django 2.2.7 on 2019-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0003_auto_20191219_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_notebook_product_page',
            name='brand',
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='camera_spec',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='dimension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='memory',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='screen_size',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='warranty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='weight',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='audio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='display',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='graphics',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='operating_system',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='processor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='product_detail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='storage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
