# Generated by Django 2.2.7 on 2019-12-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0004_auto_20191219_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_notebook_product_page',
            old_name='camera_spec',
            new_name='camera',
        ),
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='brand',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
