# Generated by Django 2.2.7 on 2019-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0005_auto_20191219_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='product_image',
            field=models.ImageField(blank=True, default='default.png', max_length=500, upload_to='Image/all_notebook_product/'),
        ),
    ]
