# Generated by Django 2.2.7 on 2019-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0007_all_notebook_product_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_notebook_product_page',
            name='slug',
            field=models.SlugField(default='TEST', unique=True),
        ),
    ]
