# Generated by Django 2.2.7 on 2019-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0009_auto_20191220_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='product_description',
            field=models.TextField(default=9999999999999999, max_length=500),
            preserve_default=False,
        ),
    ]
