# Generated by Django 2.2.7 on 2019-12-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0010_all_notebook_product_page_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='processor_speed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
