# Generated by Django 2.2.7 on 2019-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0013_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
