# Generated by Django 2.2.7 on 2019-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0015_all_notebook_product_page_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_notebook_product_page',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
