# Generated by Django 2.2.7 on 2019-12-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0016_auto_20191221_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
