# Generated by Django 2.2.7 on 2019-12-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0017_auto_20191221_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_notebook_product_page',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
