# Generated by Django 2.2.7 on 2019-12-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_shop_online_app', '0019_order_orderitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ebooks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
